### ISSUE TITLE
Class name change every time snapshot test runs

### ISSUE THREAD

**Issue by jarvisluong** [kentcdodds/jest-cypress-react-babel-webpack#18]
I’m watching the lesson: “Generate serialized values with Jest snapshot” and I noticed that the className for the wrapper div is changing every time it is running. How does jest snapshot deal with that?  https://github.com/kentcdodds/jest-cypress-react-babel-webpack/blob/egghead-2018/config-jest-06/src/shared/__tests__/__snapshots__/calculator-display.js.snap

**Comment by kentcdodds** [comment]
Hi @jarvisluong!

Nice eye! I'm pretty sure that was actually a fluke with bad editing 😬 The emotion class name will only change if the styles change, which is why jest-emotion is good to use when using emotion and snapshots.
