### ISSUE TITLE
Problems in Configure Jest For Testing JS Applications In Testing JavaScript Course

### ISSUE THREAD

**Issue by interglobalmedia** [kentcdodds/jest-cypress-react-babel-webpack#19]
I am on section one, Install and run Jest, and when I did an npm i, certain plugins which were in the package.json which I got from Github, did not install when I ran npm i. Then I installed them separately. However, when I ran npm test after installing a couple of babel related plugins (babel-plugin-emotion, 
@babel
/plugin-proposal-object-rest-spread, 
@babel
/plugin-proposal-class-properties, 
@babel
/plugin-syntax-dynamic-import@7.2.0), I got the following error:

npm test

1_install_and_run_jest@1.0.0 test /Users/mariacam/Development/testing-javascript/configure_jest_for_testing_js_apps/1_install_and_run_jest jest
FAIL src/tests/example.test.js
● Test suite failed to run

Cannot find module 'react-loadable/babel' from '/Users/mariacam/Development/testing-javascript/configure_jest_for_testing_js_apps/1_install_and_run_jest'
And when I tried to install the plugin, I got the following:

npm i react-loadable/babel -D ⏎
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/react-loadable/babel.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/mariacam/.npm/_logs/2019-06-12T12_21_50_326Z-debug.log

I have no problems communicating with Github, so I don't know why I am getting that part of the error message. I tried to find an answer
to this problem, but no luck so far. I am using Node 11.14.

Note: I think the package.json (July, 2018) has to be updated a bit.

**Comment by interglobalmedia** [comment]
Well, miraculously, when I went through the code I had gotten from the repo here again, and then rm -rfed node_modules and then re-installed, the test passed. However, some of the plugins are on their way out as well as there being a lot of vulnerabilities.

**Comment by DanceParty** [comment]
Try checking the `master` branch for a more up-to-date list of packages :)

```
{
  "name": "calculator",
  "version": "1.0.0",
  "description": "See how to configure Jest and Cypress with React, Babel, and Webpack",
  "main": "index.js",
  "scripts": {
    "test": "is-ci \"test:coverage\" \"test:watch\"",
    "test:coverage": "jest --coverage",
    "test:watch": "jest --watch",
    "test:debug": "node --inspect-brk ./node_modules/jest/bin/jest.js --runInBand --watch",
    "cy:run": "cypress run",
    "cy:open": "cypress open",
    "test:e2e": "is-ci \"test:e2e:run\" \"test:e2e:dev\"",
    "pretest:e2e:run": "npm run build",
    "test:e2e:run": "start-server-and-test start http://localhost:8080 cy:run",
    "test:e2e:dev": "start-server-and-test dev http://localhost:8080 cy:open",
    "dev": "npm-run-all --parallel dev:*",
    "dev:server": "node server",
    "dev:client": "webpack-dev-server --mode=development",
    "build": "webpack --mode=production",
    "postbuild": "cp ./public/index.html ./dist/index.html",
    "start": "npm-run-all --parallel start:*",
    "start:server": "node server",
    "start:client": "serve --no-clipboard --single --listen 8080 dist",
    "format": "prettier \"**/*.+(js|json|less|css|ts|tsx|md)\" --write",
    "lint": "jest --config test/jest.lint.js",
    "validate": "npm run test:coverage && npm run test:e2e:run",
    "postinstall": "cd server && yarn",
    "netlify": "npm-run-all --parallel test:coverage build && cp -r coverage/lcov-report dist/lcov-report",
    "setup": "yarn && npm run validate"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged && npm run test:e2e:run"
    }
  },
  "keywords": [],
  "author": "Kent C. Dodds <kent@doddsfamily.us> (http://kentcdodds.com/)",
  "license": "GPL-3.0",
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.4.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.4.2",
    "@emotion/babel-preset-css-prop": "^10.0.9",
    "babel-loader": "^8.0.2",
    "babel-plugin-dynamic-import-node": "^2.1.0",
    "css-loader": "^2.1.1",
    "cypress": "^3.1.0",
    "cypress-testing-library": "^2.2.1",
    "eslint": "^5.6.0",
    "eslint-config-cypress": "^0.28.0",
    "eslint-config-kentcdodds": "^14.0.4",
    "eslint-import-resolver-jest": "^2.1.1",
    "file-loader": "^3.0.1",
    "husky": "^1.3.1",
    "identity-obj-proxy": "^3.0.0",
    "is-ci-cli": "^1.1.1",
    "jest": "^24.5.0",
    "jest-dom": "^3.1.3",
    "jest-emotion": "^10.0.10",
    "jest-runner-eslint": "^0.7.3",
    "jest-watch-select-projects": "^0.1.1",
    "jest-watch-typeahead": "^0.2.0",
    "lint-staged": "^8.1.5",
    "npm-run-all": "^4.1.3",
    "prettier": "^1.14.3",
    "prop-types": "^15.6.2",
    "react-testing-library": "^6.0.3",
    "serve": "^10.0.2",
    "start-server-and-test": "^1.7.1",
    "style-loader": "^0.23.0",
    "test-data-bot": "^0.8.0",
    "webpack": "^4.19.1",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.9"
  },
  "dependencies": {
    "@emotion/core": "^10.0.10",
    "@emotion/styled": "^10.0.10",
    "@reach/component-component": "^0.1.1",
    "@reach/router": "^1.2.0",
    "axios": "^0.18.0",
    "emotion-theming": "^10.0.10",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-loadable": "^5.4.0",
    "react-point": "^3.0.1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/kentcdodds/jest-cypress-react-babel-webpack.git"
  },
  "bugs": {
    "url": "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/issues"
  },
  "homepage": "https://github.com/kentcdodds/jest-cypress-react-babel-webpack#readme"
}
```

**Comment by interglobalmedia** [comment]
Thanks. But then the course should also be updated since we access various branches through the course that are NOT updated. This can get to be very confusing.

**Comment by interglobalmedia** [comment]
And it isn't the egghead course I am taking. It's the comprehensive testing javascript of which this is only a part.

**Comment by kentcdodds** [comment]
An update is coming :-)

**Comment by interglobalmedia** [comment]
Great! Thanks @kentcdodds.

**Comment by kentcdodds** [comment]
I've updated the master branch and all dependencies have been updated. I'll be re-recording videos with the changes, but you should be able to checkout the current master branch to see what's changed :)
