### ISSUE TITLE
react-testing-library has changed to @testing-library/react

### ISSUE THREAD

**Issue by LluisArevalo** [kentcdodds/jest-cypress-react-babel-webpack#22]
When we try to install the dev-dependency `react-testing-library`, it appears an error importing the modules indicating that we should use `@testing-library/react` instead.

The steps that I used to correct the error are:

1. Install the `@testing-library/react` library as a dev-dependency.
2. Import `@testing-library/react/cleanup-after-each` & `{render}` from `@testing-library/react`

After that, everything has worked perfectly!

**Comment by kentcdodds** [comment]
I'm currently working on an update to testingjavascript.com right now :)

Thanks!
