### ISSUE TITLE
Chaining Cy commands in the calculator.js file confuses 'findBy...' in Cypress

### ISSUE THREAD

**Issue by Rehabescapi** [kentcdodds/jest-cypress-react-babel-webpack#27]
Following from video 5. Chaining the cy commands after cy.visit will result in these following errors:

container.querySelectorAll is not a function

Timed out retrying: Expected to find element: 'findByText(/^\+$/)', but never found it.

"expected { Object (selector) } to have text '3' "

Issue is resolved is the user restarts a 'cy.findBy...' when they need to select another element.

**Comment by kentcdodds** [comment]
Hi @Rehabescapi,

I *think* that this has now been resolved thanks to https://github.com/testing-library/cypress-testing-library/pull/100 (just an hour ago).

Thanks!
