### ISSUE TITLE
incorrect repo link in the testingjavascript.com lesson

### ISSUE THREAD

**Issue by amanmavai** [kentcdodds/jest-cypress-react-babel-webpack#32]
while watching a lesson, i observed, this lesson https://testingjavascript.com/lessons/jest-generate-a-serializable-value-with-jest-snapshots, doesn't have correct link of git branch having the related code in the lesson, esp the superheroes code.

**Comment by kentcdodds** [comment]
Hi @amanmavai,

That was just an example and intentionally didn't make it into the final repo.
