### ISSUE TITLE
cannot run tjs/jest-00

### ISSUE THREAD

**Issue by tmerlet** [kentcdodds/jest-cypress-react-babel-webpack#40]
even with the change identified here: 
https://github.com/kentcdodds/jest-cypress-react-babel-webpack/issues/39

I was not able to npm run dev here...  so not able to follow along the exercises.

**Comment by kentcdodds** [comment]
Hi @tmerlet, the intent of these workshops is not for you to follow along locally yourself. It's intended that you watch the videos and apply what you learn to your own project as needed. However, if you do want to follow along, then you *must* make sure you start by installing the dependencies in each branch you checkout. And ask new dependencies are added, you *must* make sure you're installing the *same* version as well.

The `master` branch has all the latest versions of everything, and I did fix #39 thanks to your help, so thank you!
