### ISSUE TITLE
Install and Run Jest transcript typo

### ISSUE THREAD

**Issue by antonjb** [kentcdodds/jest-cypress-react-babel-webpack#43]
The npm install snippet in the transcript is missing a dash between save and dev 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/1066856/106371664-e94db300-63a1-11eb-95dc-3384eb6e203c.png">

The snippet should read:
`npm install --save-dev jest`

Took a look through the code to see if Transcripts were here but it didn't seem like it.

**Comment by antonjb** [comment]
Also in this transcript is the following:

> 00:15 With jest installed in our dev dependencies right there, we can take a look at the known mantras directory under bin. Right here,we'll see jest, which is exactly what we want. With that installed, we can now add a test script, and we'll run simply jest in that test script.

`known mantras` should be node modules.

**Comment by kentcdodds** [comment]
Sorry I missed this somehow! I've just let the team know. Thanks for reporting!
